class DiskBuffer:
    def __init__(self, buffer_dir: str = ".buffer") -> None:
        ...

    def save(self, payload: dict) -> str:
        ...

    def load_pending(self) -> list[dict]:
        ...

    def remove(self, path: str) -> None:
        ...
