class Recorder:
    def __init__(self) -> None:
        ...

    def append_line(self, line: str) -> None:
        ...

    def get_text(self) -> str:
        ...

    def reset(self) -> None:
        ...
